### ISSUE TITLE
Please add darkmode

### ISSUE THREAD

**Issue by yojoshb** [trisdav/htmlxword#14]
hey guy, can you please add darkmode. Maybe make a little toggle button somewhere on the page so user's can toggle between drakmode and lightmode. Thanks t-dawg

**Comment by trisdav** [comment]
Here is a preview of the darkmode I'm working on: https://trisdav.github.io/htmlxword-pages/crosswords/darkmode_preview.html
It is based on your browsers darkmode setting. If a toggle button is really needed I'd open a separate issue.

**Comment by yojoshb** [comment]
Nice, looks good. Much more pleasing on the eyeballs 👌
